# fly.toml app configuration file generated for hearthbnb on 2024-12-23T13:32:36-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hearthbnb'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
